version: '3.9'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ':u0=0TI^3@lI'
    ports:
      - '3306'
    volumes:
      - './mysql/init-scripts:/docker-entrypoint-initdb.d'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: '10s'
      timeout: '5s'
      retries: 3     
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      RABBITMQ_DEFAULT_USER: 'dev'
      RABBITMQ_DEFAULT_PASS: '67lG"Bc6;taL'
    ports:
      - '5672'
      - "15672:15673"
    volumes:
      - ./rabbitmq:/etc/rabbitmq      
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 3
  app_client:
    image: 'client_service:latest'
    ports:
      - '8080:8080'
    environment:
      SERVER_PORT: '8080'
      SPRING_DATASOURCE_TYPE: 'com.zaxxer.hikari.HikariDataSource'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/testdb'
      SPRING_DATASOURCE_USERNAME: 'dev'
      SPRING_DATASOURCE_PASSWORD: ':u0=0TI^3@lI'
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: 'com.mysql.cj.jdbc.Driver'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.MySQL8Dialect'
      SPRING_JPA_HIBERNATE_DDL-AUTO: 'update'
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: '10'
      SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT: '30000'

      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_RABBITMQ_PORT: '5672'
      SPRING_RABBITMQ_USERNAME: 'dev'
      SPRING_RABBITMQ_PASSWORD: '67LG"BC6;TAL'
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  app_account:
    image: 'account_service:latest'
    ports:
      - '8081:8081'
    environment:
      SERVER_PORT: '8081'
      SPRING_DATASOURCE_TYPE: 'com.zaxxer.hikari.HikariDataSource'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/testdb'
      SPRING_DATASOURCE_USERNAME: 'dev'
      SPRING_DATASOURCE_PASSWORD: ':u0=0TI^3@lI'
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: 'com.mysql.cj.jdbc.Driver'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.MySQL8Dialect'
      SPRING_JPA_HIBERNATE_DDL-AUTO: 'update'
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: '10'
      SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT: '30000'

      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_RABBITMQ_PORT: '5672'
      SPRING_RABBITMQ_USERNAME: 'dev'
      SPRING_RABBITMQ_PASSWORD: '67LG"BC6;TAL'
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
